### ISSUE TITLE
crash with empty config

### ISSUE THREAD

**Issue by Laikulo** [Laikulo/klipper-quickflash#23]
```
Klipper QuickFlash v0.0.0-alpha (1ea92ea) by Laikulo - This KQF was packaged on 2024-05-08
   KQF is free software distributed under the terms of the GPL3
   Run kqf with the 'license' action for more information

DEBUG:root:Loading configuration from ~/.kqf/kqf.cfg
WARNING:root:There is no flavor defined for [mcu].
DEBUG:root:Loaded configuration from ~/.kqf/kqf.cfg
DEBUG:kqf:Loading MCU definitions from klipper configs
['printer', 'stepper_x', 'stepper_y', 'stepper_z', 'stepper_z1', 'stepper_z2', 'stepper_z3', 'gcode_macro _USER_VARIABLES', 'extruder', 'gcode_macro M109', 'heater_bed', 'gcode_macro M190', 'gcode_macro ACTIVATE_PROBE', 'gcode_macro DEACTIVATE_PROBE', 'probe', 'heater_fan hotend_fan', 'fan', 'controller_fan controller_fan', 'gcode_macro _SET_LEDS', 'gcode_macro _SET_LEDS_BY_NAME', 'gcode_macro _SET_ALLLEDS_BY_NAME', 'gcode_macro _SET_LOGO_LEDS', 'gcode_macro _SET_NOZZLE_LEDS', 'gcode_macro SET_LOGO_LEDS_OFF', 'gcode_macro SET_NOZZLE_LEDS_ON', 'gcode_macro SET_NOZZLE_LEDS_OFF', 'gcode_macro STATUS_LEDS', 'display', 'output_pin beeper', 'neopixel btt_mini12864', 'delayed_gcode setdisplayneopixel', 'temperature_sensor RaspberryPi', 'temperature_sensor mcu', 'temperature_sensor toolhead_mcu', 'temperature_sensor Chamber', 'gcode_macro LIGHT_OFF', 'gcode_macro LIGHT_ON', 'output_pin caselight', 'neopixel status_leds', 'adxl345', 'resonance_tester', 'gcode_macro TEST_RESONANCES', 'gcode_macro AXES_SHAPER_CALIBRATION', 'gcode_macro BELTS_SHAPER_CALIBRATION', 'gcode_macro EXCITATE_AXIS_AT_FREQ', 'gcode_macro VIBRATIONS_CALIBRATION', 'gcode_macro START_FILTER', 'gcode_macro STOP_FILTER', 'delayed_gcode _STOP_FILTER_DELAYED', 'fan_generic filter', 'gcode_macro _MMU_ERROR_CHECK1', 'gcode_macro _MMU_ERROR_CHECK2', 'gcode_macro _MMU_CHECK_STATE', 'gcode_macro _MMU_CUT_TIP', 'gcode_macro _FILAMETRIX_MOVE_TO_CUTTER_PIN', 'gcode_macro _FILAMETRIX_DO_CUT_MOTION', 'gcode_macro _FILAMETRIX_GANTRY_SERVO_DOWN', 'gcode_macro _FILAMETRIX_GANTRY_SERVO_UP', 'gcode_macro _MMU_FORM_TIP', 'tmc2209 stepper_mmu_gear', 'stepper_mmu_gear', 'tmc2209 stepper_mmu_selector', 'stepper_mmu_selector', 'mmu_servo mmu_servo', 'mmu_encoder mmu_encoder', 'mmu', 'gcode_macro _MMU_Variables', 'gcode_macro _MMU_PARK', 'gcode_macro _MMU_SAVE_POSITION', 'gcode_macro _MMU_RESTORE_POSITION', 'gcode_macro _MMU_CLEAR_POSITION', 'gcode_macro _MMU_AUTO_HOME', 'gcode_macro _MMU_PRE_UNLOAD', 'gcode_macro _MMU_POST_FORM_TIP', 'gcode_macro _MMU_POST_UNLOAD', 'gcode_macro _MMU_PRE_LOAD', 'gcode_macro _MMU_POST_LOAD', 'gcode_macro _MMU_LOAD_SEQUENCE', 'gcode_macro _MMU_UNLOAD_SEQUENCE', 'save_variables', 'gcode_macro T0', 'gcode_macro T1', 'gcode_macro T2', 'gcode_macro T3', 'gcode_macro T4', 'gcode_macro T5', 'gcode_macro T6', 'gcode_macro T7', 'gcode_macro T8', 'gcode_macro MMU__EJECT', 'gcode_macro MMU__HOME', 'gcode_macro MMU__STATUS', 'gcode_macro MMU__MOTORS_OFF', 'gcode_macro MMU__SERVO', 'gcode_macro MMU__SELECT_TOOL', 'gcode_macro MMU__SELECT_BYPASS', 'gcode_macro MMU__LOAD_BYPASS', 'gcode_macro MMU__RECOVER', 'gcode_macro MMU__PRELOAD', 'gcode_macro MMU__CHECK_GATE', 'gcode_macro MMU_CHANGE_TOOL_STANDALONE', 'gcode_macro MMU_CHECK_GATES', 'gcode_macro _MMU_ACTION_CHANGED', 'gcode_macro _MMU_PRINT_STATE_CHANGED', 'gcode_macro _MMU_GATE_MAP_CHANGED', 'gcode_macro _MMU_SET_LED', 'delayed_gcode _MMU_RESET_LED', 'mmu_led_effect mmu_breathing_red', 'mmu_led_effect mmu_white_slow', 'mmu_led_effect mmu_white_fast', 'mmu_led_effect mmu_strobe', 'mmu_led_effect mmu_green', 'mmu_led_effect mmu_orange', 'mmu_led_effect mmu_curtain', 'mmu_led_effect mmu_sparkle', 'gcode_macro BED_MESH_CALIBRATE', 'gcode_macro _ADAPTIVE_MESH_VARIABLES', 'gcode_macro COMPUTE_MESH_PARAMETERS', 'gcode_macro ADAPTIVE_BED_MESH', 'gcode_macro _DO_ADAPTIVE_MESH', 'bed_mesh', 'tmc2209 stepper_x', 'tmc2209 stepper_y', 'firmware_retraction', 'input_shaper', 'gcode_macro QUAD_GANTRY_LEVEL', 'gcode_macro _TILT_CALIBRATE', 'quad_gantry_level', 'virtual_sdcard', 'exclude_object', 'idle_timeout', 'pause_resume', 'display_status', 'respond', 'force_move', 'gcode_arcs', 'gcode_macro CANCEL_PRINT', 'gcode_macro END_PRINT', 'gcode_macro PARK', 'gcode_macro PAUSE', 'gcode_macro RESUME', 'gcode_macro START_PRINT', 'gcode_macro _MODULE_PRIMELINE', 'gcode_macro _MODULE_HEATSOAK_BED', 'gcode_macro _MODULE_HEATSOAK_CHAMBER', 'gcode_macro _MODULE_TILTING', 'gcode_macro _MODULE_EXTRUDER_HEATING', 'gcode_macro _MODULE_PURGE', 'gcode_macro _MODULE_CLEAN', 'gcode_macro _MODULE_Z_CALIB', 'gcode_macro _MODULE_BED_MESH', 'gcode_macro _MODULE_EXTRUDER_PREHEATING', 'gcode_macro _MODULE_CUSTOM1', 'gcode_macro _MODULE_CUSTOM2', 'gcode_macro _MODULE_CUSTOM3', 'gcode_macro _CG28', 'homing_override', 'gcode_macro _GOTO_Z_PROBE', 'gcode_macro CALIBRATE', 'gcode_macro _FLOW_CALIB_VARIABLES', 'gcode_macro FLOW_MULTIPLIER_CALIBRATION', 'gcode_macro COMPUTE_FLOW_MULTIPLIER', 'gcode_macro PRESSURE_ADVANCE_CALIBRATION', 'gcode_macro CHANGE_FILAMENT', 'gcode_macro UNLOAD_FILAMENT', 'gcode_macro LOAD_FILAMENT', 'gcode_macro _TIP_SHAPING', 'gcode_macro HEATSOAK_CHAMBER', 'gcode_macro _WAIT_CHAMBER_TEMP', 'gcode_macro HEATSOAK_BED', 'gcode_macro PRIMELINE', 'gcode_macro CLEAN_NOZZLE', 'gcode_macro PURGE', 'gcode_macro _CONDITIONAL_MOVE_TO_PURGE_BUCKET', 'gcode_macro _LOW_TEMP_CHECK', 'gcode_macro M701', 'gcode_macro M702', 'gcode_macro M600', 'gcode_macro M125', 'gcode_macro M900', 'gcode_macro M204', 'gcode_macro M205', 'gcode_macro G00', 'gcode_macro G01', 'gcode_macro G02', 'gcode_macro G03', 'gcode_macro G04', 'gcode_macro _SEARCH_VARS', 'delayed_gcode KLIPPAIN_STARTUP', 'gcode_macro _KLIPPAIN_STARTUP', 'gcode_macro _INIT_TMC2240', 'gcode_macro _INIT_CHECKPROBECONF', 'gcode_macro _INIT_MCU_VER', 'gcode_macro _INIT_CHECK_MMU', 'gcode_macro _INIT_USERCUSTOM', 'gcode_shell_command system_info', 'gcode_shell_command plot_graph', 'tmc2209 stepper_z', 'tmc2209 stepper_z1', 'tmc2209 stepper_z2', 'tmc2209 stepper_z3', 'mcu', 'board_pins mcu_manufacturer', 'board_pins octopus_mcu', 'mcu toolhead', 'board_pins toolhead_manufacturer', 'board_pins sb2040_mcu', 'mcu mmu', 'board_pins mmu_manufacturer', 'board_pins mmu_mcu', 'delayed_gcode welcome', 'controller_fan toolhead_fan', 'gcode_macro servo_loop']
DEBUG:kqf:Loaded 3 MCUs definitions from Klipper: [mcu, toolhead, mmu]
DEBUG:kqf:Augmenting mcu configs from klipper config
DEBUG:kqf:Augmenting mcu with klipper config
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./kqf.pyz/__main__.py", line 3, in <module>
  File "./kqf.pyz/kqf/entrypoint.py", line 13, in entrypoint
  File "./kqf.pyz/kqf/entrypoint.py", line 78, in go
  File "./kqf.pyz/kqf/cli.py", line 18, in main
  File "./kqf.pyz/kqf/cli.py", line 47, in entrypoint
  File "./kqf.pyz/kqf/cli.py", line 368, in cmd_dump_mcu
  File "./kqf.pyz/kqf/kqf.py", line 78, in inventory
  File "./kqf.pyz/kqf/klipper.py", line 110, in self_extend
  File "/usr/lib/python3.7/pathlib.py", line 901, in __truediv__
    return self._make_child((key,))
  File "/usr/lib/python3.7/pathlib.py", line 688, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.7/pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by Laikulo** [comment]
This happens if an MCU is defined that does not have a flavor set.
